from __future__ import annotations

import re
import unicodedata


ESPN_TEAM_IDS: dict[str, int] = {
    "aberdeen": 256,
    "aek athens": 887,
    "aek larnaca": 4039,
    "ajax": 139,
    "ac milan": 103,
    "arsenal": 359,
    "aston villa": 362,
    "atalanta": 105,
    "atletico madrid": 1068,
    "athletic club": 93,
    "az alkmaar": 132,
    "barcelona": 83,
    "basel": 896,
    "bayer 04 leverkusen": 131,
    "bayern munchen": 132,
    "benfica": 1929,
    "bodo glimt": 2980,
    "bologna": 107,
    "borussia dortmund": 124,
    "borussia monchengladbach": 268,
    "braga": 2994,
    "brann": 620,
    "brighton": 331,
    "brighton hove albion": 331,
    "celtic": 256,
    "celta vigo": 85,
    "chelsea": 363,
    "club brugge": 570,
    "copenhagen": 400,
    "crvena zvezda": 227,
    "crystal palace": 384,
    "dinamo zagreb": 597,
    "dynamo kyiv": 330,
    "eintracht frankfurt": 125,
    "fenerbahce": 436,
    "feyenoord": 142,
    "fiorentina": 109,
    "freiburg": 126,
    "galatasaray": 432,
    "celje": 3362,
    "drita gjilan": 19243,
    "fc noah": 20712,
    "ferencvaros": 622,
    "genk": 938,
    "gent": 3611,
    "go ahead eagles": 143,
    "inter": 110,
    "juventus": 111,
    "kairat almaty": 5966,
    "kf shkendija": 8151,
    "kups kuopio": 8169,
    "jagiellonia bialystok": 11505,
    "lausanne sports": 11551,
    "lech poznan": 551,
    "legia warszawa": 557,
    "lille": 166,
    "lazio": 112,
    "liverpool": 364,
    "ludogorets razgrad": 13018,
    "lyon": 167,
    "maccabi tel aviv": 611,
    "maccabi haifa": 611,
    "mainz": 2950,
    "malmo": 3644,
    "manchester united": 360,
    "manchester city": 382,
    "marseille": 176,
    "midtjylland": 572,
    "molde": 2715,
    "monaco": 174,
    "napoli": 114,
    "newcastle united": 361,
    "nice": 2502,
    "nottingham forest": 393,
    "nk celje": 3362,
    "omonia nicosia": 617,
    "olympiacos": 435,
    "paok": 605,
    "panathinaikos": 443,
    "paris saint germain": 160,
    "porto": 437,
    "psv": 148,
    "qarabag": 10414,
    "qarabag fk": 10414,
    "rangers": 257,
    "rakow czestochowa": 21005,
    "rayo vallecano": 101,
    "real betis": 244,
    "real madrid": 86,
    "real sociedad": 89,
    "red bull salzburg": 2790,
    "rb leipzig": 11420,
    "rijeka": 2988,
    "roma": 104,
    "samsunspor": 11429,
    "sevilla": 243,
    "shakhtar donetsk": 493,
    "servette": 20835,
    "slavia praha": 558,
    "slovan bratislava": 521,
    "sigma olomouc": 609,
    "sparta praha": 433,
    "sporting cp": 2250,
    "strasbourg": 180,
    "stuttgart": 134,
    "sturm graz": 337,
    "tottenham hotspur": 367,
    "union saint gilloise": 7603,
    "utrecht": 151,
    "valencia": 94,
    "viktoria plzen": 11706,
    "villarreal": 102,
    "west ham united": 371,
    "young boys": 2722,
    "zrinjski mostar": 5239,
}

ALIASES: dict[str, str] = {
    "ac sparta praha": "sparta praha",
    "arsenal fc": "arsenal",
    "as monaco": "monaco",
    "as roma": "roma",
    "aston villa fc": "aston villa",
    "atalanta bc": "atalanta",
    "athletic bilbao": "athletic club",
    "atl madrid": "atletico madrid",
    "atletico": "atletico madrid",
    "atletico de madrid": "atletico madrid",
    "ac milan": "ac milan",
    "b dortmund": "borussia dortmund",
    "barca": "barcelona",
    "bayer leverkusen": "bayer 04 leverkusen",
    "bayern": "bayern munchen",
    "bayern munich": "bayern munchen",
    "bode glimt": "bodo glimt",
    "bodoglimt": "bodo glimt",
    "bod glimt": "bodo glimt",
    "borussia dortmund gmbh co kgaa": "borussia dortmund",
    "borussia m gladbach": "borussia monchengladbach",
    "borussia mg": "borussia monchengladbach",
    "borussia moenchengladbach": "borussia monchengladbach",
    "borussia monchengladbach": "borussia monchengladbach",
    "borussia mönchengladbach": "borussia monchengladbach",
    "m gladbach": "borussia monchengladbach",
    "monchengladbach": "borussia monchengladbach",
    "moenchengladbach": "borussia monchengladbach",
    "bsc young boys": "young boys",
    "celtic fc": "celtic",
    "celta": "celta vigo",
    "club brugge kv": "club brugge",
    "brighton": "brighton",
    "brighton and hove albion": "brighton hove albion",
    "brighton hove albion": "brighton hove albion",
    "dortmund": "borussia dortmund",
    "drita": "drita gjilan",
    "dynamo kiev": "dynamo kyiv",
    "ferencvaros tc": "ferencvaros",
    "fc barcelona": "barcelona",
    "fc bayern munchen": "bayern munchen",
    "fc bayern munich": "bayern munchen",
    "fc copenhagen": "copenhagen",
    "fc kobenhavn": "copenhagen",
    "fc midtjylland": "midtjylland",
    "fc noah": "fc noah",
    "fc porto": "porto",
    "hsk zrinjski mostar": "zrinjski mostar",
    "zrinjski": "zrinjski mostar",
    "zrinjski mostar": "zrinjski mostar",
    "fenerbahce sk": "fenerbahce",
    "feyenooord": "feyenoord",
    "florentina": "fiorentina",
    "frankfurt": "eintracht frankfurt",
    "gnk dinamo": "dinamo zagreb",
    "gnk dinamo zagreb": "dinamo zagreb",
    "jagiellonia": "jagiellonia bialystok",
    "jagiellonia bialystok": "jagiellonia bialystok",
    "kaa gent": "gent",
    "inter milan": "inter",
    "internazionale": "inter",
    "krc genk": "genk",
    "kuopion palloseura": "kups kuopio",
    "kups": "kups kuopio",
    "lausanne": "lausanne sports",
    "lausanne sport": "lausanne sports",
    "lausanne sports": "lausanne sports",
    "leverkusen": "bayer 04 leverkusen",
    "leverkusen": "bayer 04 leverkusen",
    "liverpool fc": "liverpool",
    "m tel aviv": "maccabi tel aviv",
    "maccabi tel aviv fc": "maccabi tel aviv",
    "maccabi haifa": "maccabi haifa",
    "malmo ff": "malmo",
    "man city": "manchester city",
    "milan": "ac milan",
    "molde fk": "molde",
    "man united": "manchester united",
    "man utd": "manchester united",
    "manchester utd": "manchester united",
    "manchester united fc": "manchester united",
    "newcastle": "newcastle united",
    "newcastle utd": "newcastle united",
    "nott m forest": "nottingham forest",
    "nottm forest": "nottingham forest",
    "nk celje": "nk celje",
    "omonia": "omonia nicosia",
    "olympiacos piraeus": "olympiacos",
    "olympiakos": "olympiacos",
    "panathinaiko": "panathinaikos",
    "panathinaikos fc": "panathinaikos",
    "paris": "paris saint germain",
    "paris sg": "paris saint germain",
    "psg": "paris saint germain",
    "paok salonika": "paok",
    "paok saloniki": "paok",
    "qarabag": "qarabag",
    "qarabag fk": "qarabag fk",
    "racing genk": "genk",
    "rakow": "rakow czestochowa",
    "rakow czestochowa": "rakow czestochowa",
    "rb salzburg": "red bull salzburg",
    "rbl": "rb leipzig",
    "rb leipzig": "rb leipzig",
    "rc celta": "celta vigo",
    "real sociedad": "real sociedad",
    "real betis balompie": "real betis",
    "real madrid cf": "real madrid",
    "red bull salzburg": "red bull salzburg",
    "rijeka": "rijeka",
    "royale union saint gilloise": "union saint gilloise",
    "salzburg": "red bull salzburg",
    "sevilla fc": "sevilla",
    "shakhtar": "shakhtar donetsk",
    "sc freiburg": "freiburg",
    "servette fc": "servette",
    "sigma olomouc": "sigma olomouc",
    "sk slavia praha": "slavia praha",
    "sk slovan bratislava": "slovan bratislava",
    "sk sturm graz": "sturm graz",
    "slavia prague": "slavia praha",
    "sparta prague": "sparta praha",
    "sk brann": "brann",
    "sk sigma olomouc": "sigma olomouc",
    "samsunspor": "samsunspor",
    "shkendija": "kf shkendija",
    "sporting": "sporting cp",
    "sporting clube de portugal": "sporting cp",
    "sporting lisbon": "sporting cp",
    "storm graz": "sturm graz",
    "spurs": "tottenham hotspur",
    "tottenham": "tottenham hotspur",
    "tottenham hotspur fc": "tottenham hotspur",
    "union sg": "union saint gilloise",
    "union st gilloise": "union saint gilloise",
    "valencia cf": "valencia",
    "villareal": "villarreal",
    "villarreal cf": "villarreal",
    "west ham": "west ham united",
}


def _normalize(text: str) -> str:
    text = text.casefold().translate(str.maketrans({
        "ß": "ss",
        "æ": "ae",
        "œ": "oe",
        "ø": "o",
        "đ": "d",
        "ð": "d",
        "þ": "th",
        "ł": "l",
        "ı": "i",
        "ğ": "g",
    }))
    ascii_text = (
        unicodedata.normalize("NFKD", text)
        .encode("ascii", "ignore")
        .decode("ascii")
    )
    return " ".join(re.sub(r"[^a-z0-9]+", " ", ascii_text).split())


def resolve_espn_id(*team_names: str | None) -> int | None:
    candidates: list[str] = []
    for team_name in team_names:
        if not team_name:
            continue
        normalized = _normalize(team_name)
        if normalized:
            candidates.append(ALIASES.get(normalized, normalized))

    for candidate in candidates:
        direct = ESPN_TEAM_IDS.get(candidate)
        if direct is not None:
            return direct

    for candidate in candidates:
        for key, team_id in ESPN_TEAM_IDS.items():
            if candidate.startswith(key) or key.startswith(candidate):
                return team_id

    return None
